CREATE SCHEMA IF NOT EXISTS CMS;
USE CMS;
CREATE TABLE IF NOT EXISTS usuario(
    id INT NOT NULL AUTO_INCREMENT,
    usuario VARCHAR(20) NOT NULL,
    senha VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
);
INSERT INTO usuario(usuario, senha) VALUES("daniel","123456");
CREATE TABLE IF NOT EXISTS filmes(
    id INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(20) NOT NULL,
    descricao VARCHAR(50) NOT NULL,
    foto VARCHAR(100) NOT NULL,
    video VARCHAR(100) NOT NULL,
    genero VARCHAR(15) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS logoImg(
    id INT NOT NULL AUTO_INCREMENT,
    logoGeral VARCHAR(100) NOT NULL,
    nomeSite VARCHAR(20) NOT NULL,
    logoH1 VARCHAR(100) NOT NULL,
    logoH2 VARCHAR(100) NOT NULL,
    logoF VARCHAR(100) NOT NULL,
    logoL VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS redes(
    id NOT NULL AUTO_INCREMENT,
    pint VARCHAR(25) NOT NULL,
    face VARCHAR(25) NOT NULL,
    twi VARCHAR(25) NOT NULL,
    PRIMARY KEY(id)
);