CREATE SCHEMA IF NOT EXISTS CMS;
USE CMS;
CREATE TABLE IF NOT EXISTS usuario(
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    usuario VARCHAR(30) NOT NULL,
    senha VARCHAR(30) NOT NULL,
    foto LONGBLOB NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS imagens(
    imagem LONGBLOB NOT NULL
);
/*
 nome VARCHAR(30) NOT NULL,
    descrisao VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
    id INT NOT NULL AUTO_INCREMENT,
*/
CREATE TABLE IF NOT EXISTS videos(
    id INT NOT NULL AUTO_INCREMENT,
    video LONGBLOB NOT NULL,
    nome VARCHAR(30) NOT NULL,
    descrisao VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS textos(
    id INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(40) NOT NULL,
    paragrafo LONGTEXT NOT NULL,
    PRIMARY KEY(id)
);
